"""
Database layer for FinPerson.

Uses Postgres when DATABASE_URL is set (Render provides this automatically
when you attach a Postgres instance), and falls back to a local SQLite file
for development so `python server.py` works with zero setup.

Both paths expose the same three functions the app needs:
    get_or_create_user(google_sub, name, email, picture) -> user dict
    get_state(user_id)  -> dict or None
    save_state(user_id, state_dict)
    log_choice(user_id, persona, difficulty, choice)
"""

import json
import os
import secrets
import sqlite3
import time
from contextlib import contextmanager

DATABASE_URL = os.environ.get("DATABASE_URL", "")
SQLITE_PATH = os.environ.get("SQLITE_PATH", "finperson.db")

IS_POSTGRES = DATABASE_URL.startswith(("postgres://", "postgresql://"))

if IS_POSTGRES:
    import psycopg
    # Render's DATABASE_URL sometimes uses the deprecated postgres:// scheme.
    _PG_URL = DATABASE_URL.replace("postgres://", "postgresql://", 1)


@contextmanager
def _conn():
    if IS_POSTGRES:
        with psycopg.connect(_PG_URL) as conn:
            yield conn
    else:
        conn = sqlite3.connect(SQLITE_PATH)
        conn.row_factory = sqlite3.Row
        try:
            yield conn
            conn.commit()
        finally:
            conn.close()


def _ph(n):
    """Placeholder string: %s for postgres, ? for sqlite."""
    mark = "%s" if IS_POSTGRES else "?"
    return ", ".join([mark] * n)


def ping():
    """Cheapest possible round-trip to confirm the database is reachable —
    for /health, which may be polled every few seconds. Raises on failure;
    the caller decides what that means for the response."""
    with _conn() as conn:
        conn.cursor().execute("SELECT 1")


def init_db():
    ddl_users = """
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER PRIMARY KEY {autoinc},
            google_sub TEXT UNIQUE,
            email TEXT UNIQUE,
            password_hash TEXT,
            name TEXT,
            picture TEXT,
            is_admin INTEGER DEFAULT 0,
            research_participant_id TEXT,
            created_at REAL
        )
    """.format(autoinc="GENERATED BY DEFAULT AS IDENTITY" if IS_POSTGRES else "AUTOINCREMENT")
    ddl_states = """
        CREATE TABLE IF NOT EXISTS sandbox_states (
            user_id INTEGER PRIMARY KEY,
            state_json TEXT NOT NULL,
            updated_at REAL
        )
    """
    ddl_choices = """
        CREATE TABLE IF NOT EXISTS scenario_choices (
            id INTEGER PRIMARY KEY {autoinc},
            user_id INTEGER,
            persona TEXT,
            difficulty TEXT,
            choice TEXT,
            decision_index INTEGER,
            wellbeing INTEGER,
            zone TEXT,
            archetype_expected INTEGER,
            gap INTEGER,
            trigger_kind TEXT,
            characteristic_drift INTEGER,
            session_id TEXT,
            created_at REAL
        )
    """.format(autoinc="GENERATED BY DEFAULT AS IDENTITY" if IS_POSTGRES else "AUTOINCREMENT")
    ddl_research_participants = """
        CREATE TABLE IF NOT EXISTS research_participants (
            id INTEGER PRIMARY KEY {autoinc},
            user_id INTEGER UNIQUE,
            participant_id TEXT UNIQUE NOT NULL,
            consent_status INTEGER DEFAULT 0,
            consent_version TEXT DEFAULT 'v1',
            consented_at REAL,
            withdrawn_at REAL,
            created_at REAL,
            updated_at REAL
        )
    """.format(autoinc="GENERATED BY DEFAULT AS IDENTITY" if IS_POSTGRES else "AUTOINCREMENT")
    ddl_consent_records = """
        CREATE TABLE IF NOT EXISTS consent_records (
            id INTEGER PRIMARY KEY {autoinc},
            user_id INTEGER,
            participant_id TEXT,
            consent_status INTEGER DEFAULT 0,
            consent_version TEXT DEFAULT 'v1',
            source TEXT,
            created_at REAL,
            updated_at REAL
        )
    """.format(autoinc="GENERATED BY DEFAULT AS IDENTITY" if IS_POSTGRES else "AUTOINCREMENT")
    ddl_assessment_sessions = """
        CREATE TABLE IF NOT EXISTS assessment_sessions (
            id INTEGER PRIMARY KEY {autoinc},
            user_id INTEGER,
            participant_id TEXT,
            stage TEXT,
            completed INTEGER DEFAULT 0,
            model_version TEXT,
            created_at REAL,
            updated_at REAL
        )
    """.format(autoinc="GENERATED BY DEFAULT AS IDENTITY" if IS_POSTGRES else "AUTOINCREMENT")
    ddl_assessment_answers = """
        CREATE TABLE IF NOT EXISTS assessment_answers (
            id INTEGER PRIMARY KEY {autoinc},
            session_id INTEGER,
            question_key TEXT,
            answer TEXT,
            score REAL,
            model_version TEXT,
            created_at REAL
        )
    """.format(autoinc="GENERATED BY DEFAULT AS IDENTITY" if IS_POSTGRES else "AUTOINCREMENT")
    ddl_profile_snapshots = """
        CREATE TABLE IF NOT EXISTS profile_snapshots (
            id INTEGER PRIMARY KEY {autoinc},
            user_id INTEGER,
            participant_id TEXT,
            scored_axes TEXT,
            persona_hypothesis TEXT,
            confidence REAL,
            model_version TEXT,
            created_at REAL
        )
    """.format(autoinc="GENERATED BY DEFAULT AS IDENTITY" if IS_POSTGRES else "AUTOINCREMENT")
    ddl_practice_runs = """
        CREATE TABLE IF NOT EXISTS practice_runs (
            id INTEGER PRIMARY KEY {autoinc},
            user_id INTEGER,
            participant_id TEXT,
            scenario_id TEXT,
            outcome TEXT,
            model_version TEXT,
            created_at REAL
        )
    """.format(autoinc="GENERATED BY DEFAULT AS IDENTITY" if IS_POSTGRES else "AUTOINCREMENT")
    ddl_practice_decisions = """
        CREATE TABLE IF NOT EXISTS practice_decisions (
            id INTEGER PRIMARY KEY {autoinc},
            run_id INTEGER,
            user_id INTEGER,
            participant_id TEXT,
            choice TEXT,
            consequence TEXT,
            model_version TEXT,
            created_at REAL
        )
    """.format(autoinc="GENERATED BY DEFAULT AS IDENTITY" if IS_POSTGRES else "AUTOINCREMENT")
    ddl_goals = """
        CREATE TABLE IF NOT EXISTS goals (
            id INTEGER PRIMARY KEY {autoinc},
            user_id INTEGER,
            participant_id TEXT,
            title TEXT,
            status TEXT,
            created_at REAL,
            updated_at REAL
        )
    """.format(autoinc="GENERATED BY DEFAULT AS IDENTITY" if IS_POSTGRES else "AUTOINCREMENT")
    ddl_journal_entries = """
        CREATE TABLE IF NOT EXISTS journal_entries (
            id INTEGER PRIMARY KEY {autoinc},
            user_id INTEGER,
            participant_id TEXT,
            topic TEXT,
            entry_text TEXT,
            created_at REAL
        )
    """.format(autoinc="GENERATED BY DEFAULT AS IDENTITY" if IS_POSTGRES else "AUTOINCREMENT")
    ddl_report_entitlements = """
        CREATE TABLE IF NOT EXISTS report_entitlements (
            id INTEGER PRIMARY KEY {autoinc},
            user_id INTEGER,
            participant_id TEXT,
            report_type TEXT,
            entitlement TEXT,
            purchased INTEGER DEFAULT 0,
            created_at REAL,
            expires_at REAL
        )
    """.format(autoinc="GENERATED BY DEFAULT AS IDENTITY" if IS_POSTGRES else "AUTOINCREMENT")
    ddl_learning_progress = """
        CREATE TABLE IF NOT EXISTS learning_progress (
            user_id INTEGER PRIMARY KEY,
            progress_json TEXT NOT NULL,
            updated_at REAL
        )
    """
    ddl_idm_state = """
        CREATE TABLE IF NOT EXISTS idm_state (
            user_id INTEGER PRIMARY KEY,
            state_json TEXT NOT NULL,
            updated_at REAL
        )
    """
    ddl_achievements = """
        CREATE TABLE IF NOT EXISTS achievements (
            user_id INTEGER PRIMARY KEY,
            unlocked_json TEXT NOT NULL,
            updated_at REAL
        )
    """
    ddl_research_exports = """
        CREATE TABLE IF NOT EXISTS research_exports (
            id INTEGER PRIMARY KEY {autoinc},
            user_id INTEGER,
            export_type TEXT,
            query TEXT,
            schema_version TEXT,
            requester TEXT,
            row_count INTEGER,
            approved INTEGER DEFAULT 0,
            created_at REAL
        )
    """.format(autoinc="GENERATED BY DEFAULT AS IDENTITY" if IS_POSTGRES else "AUTOINCREMENT")
    ddl_password_resets = """
        CREATE TABLE IF NOT EXISTS password_resets (
            id INTEGER PRIMARY KEY {autoinc},
            user_id INTEGER NOT NULL,
            token_hash TEXT NOT NULL,
            used INTEGER DEFAULT 0,
            expires_at REAL,
            created_at REAL
        )
    """.format(autoinc="GENERATED BY DEFAULT AS IDENTITY" if IS_POSTGRES else "AUTOINCREMENT")
    # Server copy of goals.js's per-user goal list (localStorage key
    # finperson_goal_diary) — same JSON-blob pattern as idm_state/
    # learning_progress/achievements, not the older per-row `goals` table
    # above (that one has a different shape — title/status only, no note or
    # target-amount progress — and nothing currently writes to it).
    ddl_user_goals = """
        CREATE TABLE IF NOT EXISTS user_goals (
            user_id INTEGER PRIMARY KEY,
            goals_json TEXT NOT NULL,
            updated_at REAL
        )
    """
    # Server copy of data.js's six-axis quiz profile (localStorage key
    # finperson_profile) — same one-JSON-blob-per-user pattern as user_goals
    # above. Distinct from profile_snapshots above: that's an append-only
    # research-study scoring log tied to assessment_sessions; this is the
    # single current-state row that drives live personalization (archetype
    # match, coaching content), the thing getProfile()/saveProfile() in
    # data.js read and write.
    ddl_user_profile = """
        CREATE TABLE IF NOT EXISTS user_profile (
            user_id INTEGER PRIMARY KEY,
            profile_json TEXT NOT NULL,
            updated_at REAL
        )
    """
    # Empty and unused until a real payment provider is wired up (Stripe is
    # the natural fit — no monthly fee, per-transaction cut). Schema only,
    # so the table exists and syncs to Railway/Postgres the moment it's
    # needed, without a separate migration step later.
    ddl_subscriptions = """
        CREATE TABLE IF NOT EXISTS subscriptions (
            id INTEGER PRIMARY KEY {autoinc},
            user_id INTEGER,
            provider TEXT,
            provider_customer_id TEXT,
            provider_subscription_id TEXT,
            plan TEXT,
            status TEXT,
            current_period_end REAL,
            created_at REAL,
            updated_at REAL
        )
    """.format(autoinc="GENERATED BY DEFAULT AS IDENTITY" if IS_POSTGRES else "AUTOINCREMENT")
    # One row per classroom.html game played (Trust/Public Goods/Ultimatum).
    # Anonymous by design — no user_id — so it works the same for signed-in
    # and anonymous players and never needs to be treated as personal data.
    # This is what backs the classroom's aggregate stats and CSV export: a
    # classroom playing solo against simulated opponents still generates
    # real cross-player variance to look at once enough people have played.
    ddl_classroom_plays = """
        CREATE TABLE IF NOT EXISTS classroom_plays (
            id INTEGER PRIMARY KEY {autoinc},
            game TEXT NOT NULL,
            role TEXT,
            archetype TEXT,
            detail_json TEXT,
            cohort TEXT,
            created_at REAL
        )
    """.format(autoinc="GENERATED BY DEFAULT AS IDENTITY" if IS_POSTGRES else "AUTOINCREMENT")
    # Audit log for classroom-driven nudges to a signed-in user's own
    # user_profile row (see nudgeAxis() in classroom-page.js) — one row per
    # nudge event, so "your Risk Disposition moved +4" is traceable later
    # instead of vanishing into an unlogged localStorage mutation. Tied to
    # user_id (unlike classroom_plays) because a nudge only ever happens to
    # an identifiable person's own profile, not an anonymous play.
    ddl_profile_nudge_log = """
        CREATE TABLE IF NOT EXISTS profile_nudge_log (
            id INTEGER PRIMARY KEY {autoinc},
            user_id INTEGER NOT NULL,
            axis TEXT NOT NULL,
            delta INTEGER NOT NULL,
            source TEXT,
            created_at REAL
        )
    """.format(autoinc="GENERATED BY DEFAULT AS IDENTITY" if IS_POSTGRES else "AUTOINCREMENT")
    # One row per completed FinPerson Pro Turtle Trading simulation run.
    # Gated behind an active subscription (see subscription_active() in
    # server.py) — unlike classroom_plays this is tied to user_id, since
    # results history is a per-account feature of the paid product, not an
    # anonymous aggregate.
    ddl_turtle_sessions = """
        CREATE TABLE IF NOT EXISTS turtle_sessions (
            id INTEGER PRIMARY KEY {autoinc},
            user_id INTEGER NOT NULL,
            rounds_json TEXT,
            final_rule_equity REAL,
            final_player_equity REAL,
            override_count INTEGER,
            created_at REAL
        )
    """.format(autoinc="GENERATED BY DEFAULT AS IDENTITY" if IS_POSTGRES else "AUTOINCREMENT")
    # One row per tool call the coaching agent (coach_agent.py, LLM_ENGINE=
    # agent) makes — the queryable trace of "the model decided to call X"
    # that a static system-prompt engine can't produce. run_id groups every
    # tool call made within one agent.invoke(), so a single conversation
    # turn's whole tool-use sequence can be reconstructed in order.
    ddl_agent_tool_calls = """
        CREATE TABLE IF NOT EXISTS agent_tool_calls (
            id INTEGER PRIMARY KEY {autoinc},
            run_id TEXT NOT NULL,
            user_id INTEGER,
            persona TEXT,
            tool_name TEXT NOT NULL,
            tool_input TEXT,
            tool_output TEXT,
            status TEXT NOT NULL,
            error_message TEXT,
            created_at REAL
        )
    """.format(autoinc="GENERATED BY DEFAULT AS IDENTITY" if IS_POSTGRES else "AUTOINCREMENT")
    with _conn() as conn:
        cur = conn.cursor()
        cur.execute(ddl_users)
        cur.execute(ddl_states)
        cur.execute(ddl_choices)
        cur.execute(ddl_research_participants)
        cur.execute(ddl_consent_records)
        cur.execute(ddl_assessment_sessions)
        cur.execute(ddl_assessment_answers)
        cur.execute(ddl_profile_snapshots)
        cur.execute(ddl_practice_runs)
        cur.execute(ddl_practice_decisions)
        cur.execute(ddl_goals)
        cur.execute(ddl_journal_entries)
        cur.execute(ddl_report_entitlements)
        cur.execute(ddl_learning_progress)
        cur.execute(ddl_idm_state)
        cur.execute(ddl_achievements)
        cur.execute(ddl_research_exports)
        cur.execute(ddl_password_resets)
        cur.execute(ddl_user_goals)
        cur.execute(ddl_user_profile)
        cur.execute(ddl_subscriptions)
        cur.execute(ddl_classroom_plays)
        cur.execute(ddl_profile_nudge_log)
        cur.execute(ddl_turtle_sessions)
        cur.execute(ddl_agent_tool_calls)
    _migrate()


# Columns added after the first release. CREATE TABLE IF NOT EXISTS will not
# add them to an existing database, so we apply them idempotently here.
_ADDED_COLUMNS = [
    ("users", "research_participant_id", "TEXT"),
    ("scenario_choices", "decision_index", "INTEGER"),
    ("scenario_choices", "wellbeing", "INTEGER"),
    ("scenario_choices", "zone", "TEXT"),
    ("scenario_choices", "archetype_expected", "INTEGER"),
    ("scenario_choices", "gap", "INTEGER"),
    ("scenario_choices", "trigger_kind", "TEXT"),
    ("scenario_choices", "characteristic_drift", "INTEGER"),
    ("scenario_choices", "session_id", "TEXT"),
    ("scenario_choices", "principle", "TEXT"),
    ("scenario_choices", "surface", "TEXT"),
    ("scenario_choices", "dlo_band", "TEXT"),
    ("scenario_choices", "dlo_score", "REAL"),
    ("scenario_choices", "titration", "TEXT"),
    ("scenario_choices", "predicted", "INTEGER"),
    ("scenario_choices", "prediction_correct", "INTEGER"),
    ("scenario_choices", "confidence", "REAL"),
    ("scenario_choices", "surprise", "INTEGER"),
    ("scenario_choices", "c_level", "TEXT"),
    ("scenario_choices", "primary_axis", "TEXT"),
    ("classroom_plays", "cohort", "TEXT"),
]


def _existing_columns(cur, table):
    if IS_POSTGRES:
        cur.execute(
            "SELECT column_name FROM information_schema.columns WHERE table_name = %s",
            (table,),
        )
        return {r[0] for r in cur.fetchall()}
    cur.execute(f"PRAGMA table_info({table})")
    return {r[1] for r in cur.fetchall()}


def _migrate():
    """Add any missing columns. Safe to run on every boot."""
    with _conn() as conn:
        cur = conn.cursor()
        for table, col, coltype in _ADDED_COLUMNS:
            try:
                if col not in _existing_columns(cur, table):
                    cur.execute(f"ALTER TABLE {table} ADD COLUMN {col} {coltype}")
            except Exception:
                # A concurrent boot may have added it first; ignore and continue.
                pass


def _now():
    return time.time()


def ensure_research_participant(user_id):
    if not user_id:
        return None
    with _conn() as conn:
        cur = conn.cursor()
        cur.execute(
            f"SELECT id, participant_id, consent_status, consent_version, consented_at, withdrawn_at FROM research_participants WHERE user_id = {_ph(1)}",
            (user_id,),
        )
        row = cur.fetchone()
        if row:
            participant_id = row["participant_id"]
            consent_status = row["consent_status"]
            consent_version = row["consent_version"]
        else:
            participant_id = f"rp-{secrets.token_hex(6)}"
            cur.execute(
                f"INSERT INTO research_participants (user_id, participant_id, consent_status, consent_version, created_at, updated_at) VALUES ({_ph(6)})",
                (user_id, participant_id, 0, "v1", _now(), _now()),
            )
            cur.execute(
                f"UPDATE users SET research_participant_id = {_ph(1)} WHERE id = {_ph(1)}",
                (participant_id, user_id),
            )
            consent_status = 0
            consent_version = "v1"
        return {
            "user_id": user_id,
            "participant_id": participant_id,
            "consent_status": bool(consent_status),
            "consent_version": consent_version,
        }


def get_research_consent(user_id):
    participant = ensure_research_participant(user_id)
    if not participant:
        return {"consent": False, "participant_id": None, "consent_version": "v1"}
    return {
        "consent": participant["consent_status"],
        "participant_id": participant["participant_id"],
        "consent_version": participant["consent_version"],
    }


def set_research_consent(user_id, consent, source="onboarding", version="v1"):
    participant = ensure_research_participant(user_id)
    if not participant:
        return None
    now = _now()
    with _conn() as conn:
        cur = conn.cursor()
        cur.execute(
            f"INSERT INTO consent_records (user_id, participant_id, consent_status, consent_version, source, created_at, updated_at) VALUES ({_ph(7)})",
            (user_id, participant["participant_id"], 1 if consent else 0, version, source, now, now),
        )
        cur.execute(
            f"UPDATE research_participants SET consent_status = {_ph(1)}, consent_version = {_ph(1)}, updated_at = {_ph(1)}, consented_at = {_ph(1)}, withdrawn_at = {_ph(1)} WHERE user_id = {_ph(1)}",
            (1 if consent else 0, version, now, now if consent else None, None if consent else now, user_id),
        )
    return get_research_consent(user_id)


def log_assessment_answer(user_id, payload):
    participant = ensure_research_participant(user_id)
    if not participant:
        return None
    now = _now()
    with _conn() as conn:
        cur = conn.cursor()
        cur.execute(
            f"INSERT INTO assessment_sessions (user_id, participant_id, stage, completed, model_version, created_at, updated_at) VALUES ({_ph(7)})",
            (
                user_id,
                participant["participant_id"],
                payload.get("stage", "free"),
                1 if payload.get("completed") else 0,
                payload.get("model_version", "v1"),
                now,
                now,
            ),
        )
        if IS_POSTGRES:
            cur.execute("SELECT LASTVAL()")
            session_id = cur.fetchone()[0]
        else:
            session_id = cur.lastrowid
        cur.execute(
            f"INSERT INTO assessment_answers (session_id, question_key, answer, score, model_version, created_at) VALUES ({_ph(6)})",
            (
                session_id,
                payload.get("question_key") or payload.get("question") or "question",
                json.dumps(payload.get("answer")) if isinstance(payload.get("answer"), (dict, list)) else payload.get("answer"),
                payload.get("score"),
                payload.get("model_version", "v1"),
                now,
            ),
        )
    return {"session_id": session_id, "participant_id": participant["participant_id"]}


def record_profile_snapshot(user_id, payload):
    participant = ensure_research_participant(user_id)
    if not participant:
        return None
    with _conn() as conn:
        cur = conn.cursor()
        cur.execute(
            f"INSERT INTO profile_snapshots (user_id, participant_id, scored_axes, persona_hypothesis, confidence, model_version, created_at) VALUES ({_ph(7)})",
            (
                user_id,
                participant["participant_id"],
                json.dumps(payload.get("scored_axes") or {}),
                payload.get("persona_hypothesis"),
                payload.get("confidence"),
                payload.get("model_version", "v1"),
                _now(),
            ),
        )
    return {"participant_id": participant["participant_id"]}


def record_practice_event(user_id, payload):
    participant = ensure_research_participant(user_id)
    if not participant:
        return None
    with _conn() as conn:
        cur = conn.cursor()
        cur.execute(
            f"INSERT INTO practice_runs (user_id, participant_id, scenario_id, outcome, model_version, created_at) VALUES ({_ph(6)})",
            (
                user_id,
                participant["participant_id"],
                payload.get("scenario_id"),
                payload.get("outcome"),
                payload.get("model_version", "v1"),
                _now(),
            ),
        )
        if IS_POSTGRES:
            cur.execute("SELECT LASTVAL()")
            run_id = cur.fetchone()[0]
        else:
            run_id = cur.lastrowid
        if payload.get("decision") is not None:
            cur.execute(
                f"INSERT INTO practice_decisions (run_id, user_id, participant_id, choice, consequence, model_version, created_at) VALUES ({_ph(7)})",
                (
                    run_id,
                    user_id,
                    participant["participant_id"],
                    payload.get("decision"),
                    payload.get("consequence"),
                    payload.get("model_version", "v1"),
                    _now(),
                ),
            )
    return {"run_id": run_id, "participant_id": participant["participant_id"]}


def record_goal(user_id, payload):
    participant = ensure_research_participant(user_id)
    if not participant:
        return None
    with _conn() as conn:
        cur = conn.cursor()
        cur.execute(
            f"INSERT INTO goals (user_id, participant_id, title, status, created_at, updated_at) VALUES ({_ph(6)})",
            (user_id, participant["participant_id"], payload.get("title"), payload.get("status", "active"), _now(), _now()),
        )
    return {"participant_id": participant["participant_id"]}


def record_journal_entry(user_id, payload):
    participant = ensure_research_participant(user_id)
    if not participant:
        return None
    with _conn() as conn:
        cur = conn.cursor()
        cur.execute(
            f"INSERT INTO journal_entries (user_id, participant_id, topic, entry_text, created_at) VALUES ({_ph(5)})",
            (user_id, participant["participant_id"], payload.get("topic"), payload.get("entry_text"), _now()),
        )
    return {"participant_id": participant["participant_id"]}


def record_report_entitlement(user_id, payload):
    participant = ensure_research_participant(user_id)
    if not participant:
        return None
    with _conn() as conn:
        cur = conn.cursor()
        cur.execute(
            f"INSERT INTO report_entitlements (user_id, participant_id, report_type, entitlement, purchased, created_at, expires_at) VALUES ({_ph(7)})",
            (
                user_id,
                participant["participant_id"],
                payload.get("report_type", "premium"),
                payload.get("entitlement", "free-preview"),
                1 if payload.get("purchased") else 0,
                _now(),
                payload.get("expires_at"),
            ),
        )
    return {"participant_id": participant["participant_id"]}


def record_research_export(user_id, payload):
    with _conn() as conn:
        cur = conn.cursor()
        cur.execute(
            f"INSERT INTO research_exports (user_id, export_type, query, schema_version, requester, row_count, approved, created_at) VALUES ({_ph(8)})",
            (
                user_id,
                payload.get("export_type", "research"),
                payload.get("query"),
                payload.get("schema_version", "v1"),
                payload.get("requester", "internal"),
                payload.get("row_count", 0),
                1 if payload.get("approved") else 0,
                _now(),
            ),
        )
    return {"ok": True}


def export_user_research_data(user_id):
    participant = ensure_research_participant(user_id)
    if not participant:
        return {"participant_id": None, "consent": [], "assessment_sessions": [], "assessment_answers": [], "profile_snapshots": [], "practice_runs": [], "practice_decisions": [], "goals": [], "journal_entries": [], "report_entitlements": []}
    with _conn() as conn:
        cur = conn.cursor()
        cur.execute(
            f"SELECT id, participant_id, consent_status, consent_version, source, created_at, updated_at FROM consent_records WHERE user_id = {_ph(1)} ORDER BY created_at",
            (user_id,),
        )
        consent = [
            {
                "id": r[0],
                "participant_id": r[1],
                "consent_status": bool(r[2]),
                "consent_version": r[3],
                "source": r[4],
                "created_at": r[5],
                "updated_at": r[6],
            }
            for r in cur.fetchall()
        ]
        cur.execute(
            f"SELECT id, participant_id, stage, completed, model_version, created_at, updated_at FROM assessment_sessions WHERE user_id = {_ph(1)} ORDER BY created_at",
            (user_id,),
        )
        assessment_sessions = [
            {
                "id": r[0],
                "participant_id": r[1],
                "stage": r[2],
                "completed": bool(r[3]),
                "model_version": r[4],
                "created_at": r[5],
                "updated_at": r[6],
            }
            for r in cur.fetchall()
        ]
        cur.execute(
            f"SELECT id, session_id, question_key, answer, score, model_version, created_at FROM assessment_answers WHERE session_id IN (SELECT id FROM assessment_sessions WHERE user_id = {_ph(1)}) ORDER BY created_at",
            (user_id,),
        )
        assessment_answers = [
            {
                "id": r[0],
                "session_id": r[1],
                "question_key": r[2],
                "answer": r[3],
                "score": r[4],
                "model_version": r[5],
                "created_at": r[6],
            }
            for r in cur.fetchall()
        ]
        cur.execute(
            f"SELECT id, participant_id, scored_axes, persona_hypothesis, confidence, model_version, created_at FROM profile_snapshots WHERE user_id = {_ph(1)} ORDER BY created_at",
            (user_id,),
        )
        profile_snapshots = [
            {
                "id": r[0],
                "participant_id": r[1],
                "scored_axes": json.loads(r[2]) if r[2] else None,
                "persona_hypothesis": r[3],
                "confidence": r[4],
                "model_version": r[5],
                "created_at": r[6],
            }
            for r in cur.fetchall()
        ]
        cur.execute(
            f"SELECT id, participant_id, scenario_id, outcome, model_version, created_at FROM practice_runs WHERE user_id = {_ph(1)} ORDER BY created_at",
            (user_id,),
        )
        practice_runs = [
            {
                "id": r[0],
                "participant_id": r[1],
                "scenario_id": r[2],
                "outcome": r[3],
                "model_version": r[4],
                "created_at": r[5],
            }
            for r in cur.fetchall()
        ]
        cur.execute(
            f"SELECT id, participant_id, choice, consequence, model_version, created_at FROM practice_decisions WHERE user_id = {_ph(1)} ORDER BY created_at",
            (user_id,),
        )
        practice_decisions = [
            {
                "id": r[0],
                "participant_id": r[1],
                "choice": r[2],
                "consequence": r[3],
                "model_version": r[4],
                "created_at": r[5],
            }
            for r in cur.fetchall()
        ]
        cur.execute(
            f"SELECT id, participant_id, title, status, created_at, updated_at FROM goals WHERE user_id = {_ph(1)} ORDER BY created_at",
            (user_id,),
        )
        goals = [
            {
                "id": r[0],
                "participant_id": r[1],
                "title": r[2],
                "status": r[3],
                "created_at": r[4],
                "updated_at": r[5],
            }
            for r in cur.fetchall()
        ]
        cur.execute(
            f"SELECT id, participant_id, topic, entry_text, created_at FROM journal_entries WHERE user_id = {_ph(1)} ORDER BY created_at",
            (user_id,),
        )
        journal_entries = [
            {
                "id": r[0],
                "participant_id": r[1],
                "topic": r[2],
                "entry_text": r[3],
                "created_at": r[4],
            }
            for r in cur.fetchall()
        ]
        cur.execute(
            f"SELECT id, participant_id, report_type, entitlement, purchased, created_at, expires_at FROM report_entitlements WHERE user_id = {_ph(1)} ORDER BY created_at",
            (user_id,),
        )
        report_entitlements = [
            {
                "id": r[0],
                "participant_id": r[1],
                "report_type": r[2],
                "entitlement": r[3],
                "purchased": bool(r[4]),
                "created_at": r[5],
                "expires_at": r[6],
            }
            for r in cur.fetchall()
        ]
    return {
        "participant_id": participant["participant_id"],
        "consent": consent,
        "assessment_sessions": assessment_sessions,
        "assessment_answers": assessment_answers,
        "profile_snapshots": profile_snapshots,
        "practice_runs": practice_runs,
        "practice_decisions": practice_decisions,
        "goals": goals,
        "journal_entries": journal_entries,
        "report_entitlements": report_entitlements,
    }


def export_research_dataset():
    with _conn() as conn:
        cur = conn.cursor()
        cur.execute(
            f"SELECT participant_id, consent_status, consent_version, created_at FROM research_participants ORDER BY created_at"
        )
        rows = [
            {
                "participant_id": r[0],
                "consent_status": bool(r[1]),
                "consent_version": r[2],
                "created_at_bucket": int(r[3] // 86400) if r[3] is not None else None,
            }
            for r in cur.fetchall()
        ]
    return {
        "schema_version": "v1",
        "row_count": len(rows),
        "rows": rows,
    }


def get_or_create_user(google_sub, name, email, picture):
    with _conn() as conn:
        cur = conn.cursor()
        cur.execute(
            f"SELECT id, name, email, picture FROM users WHERE google_sub = {_ph(1)}",
            (google_sub,),
        )
        row = cur.fetchone()
        if row:
            user_id = row[0]
            # Refresh profile fields in case they changed at Google.
            cur.execute(
                f"UPDATE users SET name = {_ph(1)}, email = {_ph(1)}, picture = {_ph(1)} WHERE id = {_ph(1)}",
                (name, email, picture, user_id),
            )
        else:
            cur.execute(
                f"INSERT INTO users (google_sub, name, email, picture, created_at) VALUES ({_ph(5)})",
                (google_sub, name, email, picture, time.time()),
            )
            if IS_POSTGRES:
                cur.execute(f"SELECT id FROM users WHERE google_sub = {_ph(1)}", (google_sub,))
                user_id = cur.fetchone()[0]
            else:
                user_id = cur.lastrowid
        return {"id": user_id, "name": name, "email": email, "picture": picture}


def get_state(user_id):
    with _conn() as conn:
        cur = conn.cursor()
        cur.execute(f"SELECT state_json FROM sandbox_states WHERE user_id = {_ph(1)}", (user_id,))
        row = cur.fetchone()
        if not row:
            return None
        try:
            return json.loads(row[0])
        except (TypeError, ValueError):
            return None


def save_state(user_id, state):
    payload = json.dumps(state)[:20000]  # hard cap, matches request size limits
    with _conn() as conn:
        cur = conn.cursor()
        if IS_POSTGRES:
            cur.execute(
                """INSERT INTO sandbox_states (user_id, state_json, updated_at)
                   VALUES (%s, %s, %s)
                   ON CONFLICT (user_id) DO UPDATE
                   SET state_json = EXCLUDED.state_json, updated_at = EXCLUDED.updated_at""",
                (user_id, payload, time.time()),
            )
        else:
            cur.execute(
                """INSERT INTO sandbox_states (user_id, state_json, updated_at)
                   VALUES (?, ?, ?)
                   ON CONFLICT (user_id) DO UPDATE
                   SET state_json = excluded.state_json, updated_at = excluded.updated_at""",
                (user_id, payload, time.time()),
            )


def get_learning_progress(user_id):
    with _conn() as conn:
        cur = conn.cursor()
        cur.execute(f"SELECT progress_json FROM learning_progress WHERE user_id = {_ph(1)}", (user_id,))
        row = cur.fetchone()
        if not row:
            return None
        try:
            return json.loads(row[0])
        except (TypeError, ValueError):
            return None


def save_learning_progress(user_id, progress):
    payload = json.dumps(progress)[:20000]  # hard cap, matches sandbox_states
    with _conn() as conn:
        cur = conn.cursor()
        if IS_POSTGRES:
            cur.execute(
                """INSERT INTO learning_progress (user_id, progress_json, updated_at)
                   VALUES (%s, %s, %s)
                   ON CONFLICT (user_id) DO UPDATE
                   SET progress_json = EXCLUDED.progress_json, updated_at = EXCLUDED.updated_at""",
                (user_id, payload, time.time()),
            )
        else:
            cur.execute(
                """INSERT INTO learning_progress (user_id, progress_json, updated_at)
                   VALUES (?, ?, ?)
                   ON CONFLICT (user_id) DO UPDATE
                   SET progress_json = excluded.progress_json, updated_at = excluded.updated_at""",
                (user_id, payload, time.time()),
            )


def get_idm_state(user_id):
    """Server copy of idm.js's calibration state (see IDM_KEY in idm.js) —
    previously localStorage-only, meaning it was invisible to admin analytics
    and lost on a new device. Same JSON-blob shape as learning_progress."""
    with _conn() as conn:
        cur = conn.cursor()
        cur.execute(f"SELECT state_json FROM idm_state WHERE user_id = {_ph(1)}", (user_id,))
        row = cur.fetchone()
        if not row:
            return None
        try:
            return json.loads(row[0])
        except (TypeError, ValueError):
            return None


def save_idm_state(user_id, state):
    payload = json.dumps(state)[:20000]
    with _conn() as conn:
        cur = conn.cursor()
        if IS_POSTGRES:
            cur.execute(
                """INSERT INTO idm_state (user_id, state_json, updated_at)
                   VALUES (%s, %s, %s)
                   ON CONFLICT (user_id) DO UPDATE
                   SET state_json = EXCLUDED.state_json, updated_at = EXCLUDED.updated_at""",
                (user_id, payload, time.time()),
            )
        else:
            cur.execute(
                """INSERT INTO idm_state (user_id, state_json, updated_at)
                   VALUES (?, ?, ?)
                   ON CONFLICT (user_id) DO UPDATE
                   SET state_json = excluded.state_json, updated_at = excluded.updated_at""",
                (user_id, payload, time.time()),
            )


def get_achievements(user_id):
    """List of unlocked achievement ids for this user. Achievements only ever
    add, never revert, so the server copy is just a set — union-merge on
    sync, no per-item comparison needed like idm_state requires."""
    with _conn() as conn:
        cur = conn.cursor()
        cur.execute(f"SELECT unlocked_json FROM achievements WHERE user_id = {_ph(1)}", (user_id,))
        row = cur.fetchone()
        if not row:
            return []
        try:
            return json.loads(row[0])
        except (TypeError, ValueError):
            return []


def save_achievements(user_id, unlocked):
    payload = json.dumps(list(unlocked))[:20000]
    with _conn() as conn:
        cur = conn.cursor()
        if IS_POSTGRES:
            cur.execute(
                """INSERT INTO achievements (user_id, unlocked_json, updated_at)
                   VALUES (%s, %s, %s)
                   ON CONFLICT (user_id) DO UPDATE
                   SET unlocked_json = EXCLUDED.unlocked_json, updated_at = EXCLUDED.updated_at""",
                (user_id, payload, time.time()),
            )
        else:
            cur.execute(
                """INSERT INTO achievements (user_id, unlocked_json, updated_at)
                   VALUES (?, ?, ?)
                   ON CONFLICT (user_id) DO UPDATE
                   SET unlocked_json = excluded.unlocked_json, updated_at = excluded.updated_at""",
                (user_id, payload, time.time()),
            )


def get_user_goals(user_id):
    with _conn() as conn:
        cur = conn.cursor()
        cur.execute(f"SELECT goals_json FROM user_goals WHERE user_id = {_ph(1)}", (user_id,))
        row = cur.fetchone()
        if not row:
            return None
        try:
            return json.loads(row[0])
        except (TypeError, ValueError):
            return None


def save_user_goals(user_id, goals):
    payload = json.dumps(goals)[:20000]
    with _conn() as conn:
        cur = conn.cursor()
        if IS_POSTGRES:
            cur.execute(
                """INSERT INTO user_goals (user_id, goals_json, updated_at)
                   VALUES (%s, %s, %s)
                   ON CONFLICT (user_id) DO UPDATE
                   SET goals_json = EXCLUDED.goals_json, updated_at = EXCLUDED.updated_at""",
                (user_id, payload, time.time()),
            )
        else:
            cur.execute(
                """INSERT INTO user_goals (user_id, goals_json, updated_at)
                   VALUES (?, ?, ?)
                   ON CONFLICT (user_id) DO UPDATE
                   SET goals_json = excluded.goals_json, updated_at = excluded.updated_at""",
                (user_id, payload, time.time()),
            )


def get_user_profile(user_id):
    with _conn() as conn:
        cur = conn.cursor()
        cur.execute(f"SELECT profile_json FROM user_profile WHERE user_id = {_ph(1)}", (user_id,))
        row = cur.fetchone()
        if not row:
            return None
        try:
            return json.loads(row[0])
        except (TypeError, ValueError):
            return None


def save_user_profile(user_id, blob):
    payload = json.dumps(blob)[:20000]
    with _conn() as conn:
        cur = conn.cursor()
        if IS_POSTGRES:
            cur.execute(
                """INSERT INTO user_profile (user_id, profile_json, updated_at)
                   VALUES (%s, %s, %s)
                   ON CONFLICT (user_id) DO UPDATE
                   SET profile_json = EXCLUDED.profile_json, updated_at = EXCLUDED.updated_at""",
                (user_id, payload, time.time()),
            )
        else:
            cur.execute(
                """INSERT INTO user_profile (user_id, profile_json, updated_at)
                   VALUES (?, ?, ?)
                   ON CONFLICT (user_id) DO UPDATE
                   SET profile_json = excluded.profile_json, updated_at = excluded.updated_at""",
                (user_id, payload, time.time()),
            )


def get_axis_consistency(user_id):
    """Per-axis decision consistency: how much wellbeing swings among this
    user's own decisions tagged with each primary_axis (see fbm.js
    SURFACE_AXIS). Low variance = decisions on that axis land in a similar
    place each time; high variance = erratic. Population variance computed
    in plain Python since SQLite has no built-in STDDEV/VARIANCE."""
    with _conn() as conn:
        cur = conn.cursor()
        cur.execute(
            f"""SELECT primary_axis, wellbeing FROM scenario_choices
                WHERE user_id = {_ph(1)} AND primary_axis IS NOT NULL AND wellbeing IS NOT NULL""",
            (user_id,),
        )
        by_axis = {}
        for axis, wellbeing in cur.fetchall():
            by_axis.setdefault(axis, []).append(wellbeing)

    result = {}
    for axis, values in by_axis.items():
        n = len(values)
        mean = sum(values) / n
        variance = sum((v - mean) ** 2 for v in values) / n
        result[axis] = {"count": n, "avg_wellbeing": round(mean, 1), "variance": round(variance, 1)}
    return result


def get_wellbeing_history(user_id):
    """A signed-in user's own sandbox wellbeing trajectory, for progress.html —
    a focused query (not the full export_user_data payload, which has a
    different shape and includes fields this chart doesn't need)."""
    with _conn() as conn:
        cur = conn.cursor()
        cur.execute(
            f"""SELECT wellbeing, zone, created_at FROM scenario_choices
                WHERE user_id = {_ph(1)} AND wellbeing IS NOT NULL
                ORDER BY created_at""",
            (user_id,),
        )
        return [{"wellbeing": r[0], "zone": r[1], "created_at": r[2]} for r in cur.fetchall()]


def log_choice(user_id, persona, difficulty, choice, homeostasis=None):
    """
    Records one decision. `homeostasis` optionally carries the PIPE telemetry
    for that decision so behaviour can be analysed over time:
      decision_index, wellbeing, zone, archetype_expected, gap,
      trigger_kind, characteristic_drift, session_id
    """
    h = homeostasis or {}

    def _int(v):
        try:
            return int(v)
        except (TypeError, ValueError):
            return None

    def _float(v):
        try:
            return float(v)
        except (TypeError, ValueError):
            return None

    with _conn() as conn:
        cur = conn.cursor()
        cur.execute(
            f"""INSERT INTO scenario_choices
                (user_id, persona, difficulty, choice, decision_index, wellbeing,
                 zone, archetype_expected, gap, trigger_kind, characteristic_drift,
                 session_id, principle, surface, dlo_band, dlo_score, titration,
                 predicted, prediction_correct, confidence, surprise, c_level,
                 primary_axis, created_at)
                VALUES ({_ph(24)})""",
            (
                user_id,
                str(persona)[:64],
                str(difficulty)[:16],
                str(choice)[:200],
                _int(h.get("decision_index")),
                _int(h.get("wellbeing")),
                (str(h.get("zone"))[:16] if h.get("zone") else None),
                _int(h.get("archetype_expected")),
                _int(h.get("gap")),
                (str(h.get("trigger_kind"))[:16] if h.get("trigger_kind") else None),
                (1 if h.get("characteristic_drift") else 0) if h.get("characteristic_drift") is not None else None,
                (str(h.get("session_id"))[:64] if h.get("session_id") else None),
                (str(h.get("principle"))[:64] if h.get("principle") else None),
                (str(h.get("surface"))[:64] if h.get("surface") else None),
                (str(h.get("dlo_band"))[:16] if h.get("dlo_band") else None),
                _float(h.get("dlo_score")),
                (str(h.get("titration"))[:16] if h.get("titration") else None),
                _int(h.get("predicted")),
                (1 if h.get("prediction_correct") else 0) if h.get("prediction_correct") is not None else None,
                _float(h.get("confidence")),
                _int(h.get("surprise")),
                (str(h.get("c_level"))[:8] if h.get("c_level") else None),
                (str(h.get("primary_axis"))[:32] if h.get("primary_axis") else None),
                time.time(),
            ),
        )


# ---------------------------------------------------------------- password auth

def create_password_user(email, password_hash, name):
    """Returns user dict, or None if the email is already taken."""
    with _conn() as conn:
        cur = conn.cursor()
        cur.execute(f"SELECT id FROM users WHERE email = {_ph(1)}", (email,))
        if cur.fetchone():
            return None
        cur.execute(
            f"INSERT INTO users (email, password_hash, name, created_at) VALUES ({_ph(4)})",
            (email, password_hash, name, time.time()),
        )
        if IS_POSTGRES:
            cur.execute(f"SELECT id FROM users WHERE email = {_ph(1)}", (email,))
            uid = cur.fetchone()[0]
        else:
            uid = cur.lastrowid
        return {"id": uid, "name": name, "email": email, "picture": ""}


def get_user_by_email(email):
    with _conn() as conn:
        cur = conn.cursor()
        cur.execute(
            f"SELECT id, name, email, picture, password_hash FROM users WHERE email = {_ph(1)}",
            (email,),
        )
        row = cur.fetchone()
        if not row:
            return None
        return {"id": row[0], "name": row[1], "email": row[2], "picture": row[3] or "", "password_hash": row[4]}


def set_user_password(user_id, password_hash):
    with _conn() as conn:
        cur = conn.cursor()
        cur.execute(
            f"UPDATE users SET password_hash = {_ph(1)} WHERE id = {_ph(1)}",
            (password_hash, user_id),
        )


def create_password_reset(user_id, token_hash, ttl_seconds):
    """Invalidates any earlier reset request for this user, then stores the
    new one. Only the hash is stored — same reasoning as a password hash:
    a database leak shouldn't hand out usable reset links."""
    with _conn() as conn:
        cur = conn.cursor()
        cur.execute(f"DELETE FROM password_resets WHERE user_id = {_ph(1)}", (user_id,))
        cur.execute(
            f"INSERT INTO password_resets (user_id, token_hash, used, expires_at, created_at) VALUES ({_ph(5)})",
            (user_id, token_hash, 0, time.time() + ttl_seconds, time.time()),
        )


def get_password_reset(token_hash):
    with _conn() as conn:
        cur = conn.cursor()
        cur.execute(
            f"SELECT user_id, used, expires_at FROM password_resets WHERE token_hash = {_ph(1)}",
            (token_hash,),
        )
        row = cur.fetchone()
        if not row:
            return None
        return {"user_id": row[0], "used": bool(row[1]), "expires_at": row[2]}


def consume_password_reset(token_hash):
    with _conn() as conn:
        cur = conn.cursor()
        cur.execute(f"UPDATE password_resets SET used = 1 WHERE token_hash = {_ph(1)}", (token_hash,))


# ---------------------------------------------------------------- admin

def is_admin(user_id):
    with _conn() as conn:
        cur = conn.cursor()
        cur.execute(f"SELECT is_admin FROM users WHERE id = {_ph(1)}", (user_id,))
        row = cur.fetchone()
        return bool(row and row[0])


def admin_stats():
    """Aggregate, non-personal metrics for the admin view."""
    with _conn() as conn:
        cur = conn.cursor()
        cur.execute("SELECT COUNT(*) FROM users")
        total_users = cur.fetchone()[0]
        cur.execute("SELECT COUNT(*) FROM scenario_choices")
        total_choices = cur.fetchone()[0]
        cur.execute("SELECT COUNT(*) FROM sandbox_states")
        active_sandboxes = cur.fetchone()[0]
        cur.execute(
            "SELECT persona, COUNT(*) c FROM scenario_choices "
            "GROUP BY persona ORDER BY c DESC LIMIT 11"
        )
        by_persona = [{"persona": r[0], "count": r[1]} for r in cur.fetchall()]
        day_ago = time.time() - 86400
        cur.execute(
            f"SELECT COUNT(*) FROM scenario_choices WHERE created_at > {_ph(1)}",
            (day_ago,),
        )
        choices_24h = cur.fetchone()[0]

        # --- Homeostasis telemetry (PIPE evaluation signals) ---
        cur.execute(
            "SELECT zone, COUNT(*) FROM scenario_choices "
            "WHERE zone IS NOT NULL GROUP BY zone"
        )
        zone_rows = {r[0]: r[1] for r in cur.fetchall()}
        zoned_total = sum(zone_rows.values())

        cur.execute("SELECT COUNT(*) FROM scenario_choices WHERE trigger_kind IS NOT NULL")
        trigger_total = cur.fetchone()[0]

        cur.execute("SELECT COUNT(*) FROM scenario_choices WHERE characteristic_drift = 1")
        char_drift_total = cur.fetchone()[0]

        cur.execute("SELECT AVG(wellbeing) FROM scenario_choices WHERE wellbeing IS NOT NULL")
        avg_wellbeing = cur.fetchone()[0]

        cur.execute(
            "SELECT AVG(gap) FROM scenario_choices WHERE gap IS NOT NULL"
        )
        avg_gap = cur.fetchone()[0]

        # --- Quiz-profile archetype distance (how far raw quiz answers sit
        # from a "pure" version of the matched archetype; see fbm.js
        # archetypeCloseness). Distinct from avg_gap above, which is about
        # in-sandbox decision behaviour, not the quiz itself. ---
        cur.execute("SELECT COUNT(*), AVG(confidence) FROM profile_snapshots WHERE confidence IS NOT NULL")
        snap_row = cur.fetchone()
        snapshot_count, avg_closeness = snap_row[0], snap_row[1]

        # --- Decisions by primary FBM axis (see fbm.js SURFACE_AXIS) — which
        # axis actual sandbox decisions are probing, and their avg wellbeing. ---
        cur.execute(
            """SELECT primary_axis, COUNT(*), AVG(wellbeing) FROM scenario_choices
               WHERE primary_axis IS NOT NULL GROUP BY primary_axis ORDER BY COUNT(*) DESC"""
        )
        by_axis = [
            {"axis": r[0], "count": r[1], "avg_wellbeing": round(r[2], 1) if r[2] is not None else None}
            for r in cur.fetchall()
        ]

        return {
            "total_users": total_users,
            "total_choices": total_choices,
            "active_sandboxes": active_sandboxes,
            "choices_24h": choices_24h,
            "by_persona": by_persona,
            "homeostasis": {
                "in_zone": zone_rows.get("homeostasis", 0),
                "breakdown": zone_rows.get("breakdown", 0),
                "distortion": zone_rows.get("distortion", 0),
                "zoned_total": zoned_total,
                "in_zone_pct": round((zone_rows.get("homeostasis", 0) / zoned_total) * 100, 1) if zoned_total else None,
                "triggers": trigger_total,
                "characteristic_drift": char_drift_total,
                "avg_wellbeing": round(avg_wellbeing, 1) if avg_wellbeing is not None else None,
                "avg_gap": round(avg_gap, 1) if avg_gap is not None else None,
            },
            "quiz_archetype_distance": {
                "snapshot_count": snapshot_count,
                "avg_closeness_pct": round(avg_closeness * 100, 1) if avg_closeness is not None else None,
            },
            "by_axis": by_axis,
        }


def get_user_email(user_id):
    with _conn() as conn:
        cur = conn.cursor()
        cur.execute(f"SELECT email FROM users WHERE id = {_ph(1)}", (user_id,))
        row = cur.fetchone()
    return row[0] if row else None


# ---------------------------------------------------------------- GDPR

def export_user_data(user_id):
    """Everything stored about one user, for a data-export request."""
    with _conn() as conn:
        cur = conn.cursor()
        cur.execute(
            f"SELECT id, google_sub, email, name, picture, created_at FROM users WHERE id = {_ph(1)}",
            (user_id,),
        )
        u = cur.fetchone()
        if not u:
            return None
        cur.execute(f"SELECT state_json, updated_at FROM sandbox_states WHERE user_id = {_ph(1)}", (user_id,))
        s = cur.fetchone()
        cur.execute(
            f"""SELECT persona, difficulty, choice, decision_index, wellbeing, zone,
                       archetype_expected, gap, trigger_kind, characteristic_drift, created_at
                FROM scenario_choices WHERE user_id = {_ph(1)} ORDER BY created_at""",
            (user_id,),
        )
        choices = [
            {
                "persona": r[0], "difficulty": r[1], "choice": r[2],
                "decision_index": r[3], "wellbeing": r[4], "zone": r[5],
                "archetype_expected": r[6], "gap": r[7],
                "trigger_kind": r[8], "characteristic_drift": r[9],
                "created_at": r[10],
            }
            for r in cur.fetchall()
        ]
        return {
            "account": {
                "id": u[0],
                "signed_up_with": "google" if u[1] else "email",
                "email": u[2],
                "name": u[3],
                "picture": u[4],
                "created_at": u[5],
            },
            "sandbox_state": json.loads(s[0]) if s and s[0] else None,
            "sandbox_state_updated_at": s[1] if s else None,
            "scenario_choices": choices,
        }


def delete_user(user_id):
    """Hard-delete a user and everything linked to them."""
    with _conn() as conn:
        cur = conn.cursor()
        cur.execute(f"DELETE FROM scenario_choices WHERE user_id = {_ph(1)}", (user_id,))
        cur.execute(f"DELETE FROM sandbox_states WHERE user_id = {_ph(1)}", (user_id,))
        cur.execute(f"DELETE FROM users WHERE id = {_ph(1)}", (user_id,))


def record_classroom_play(game, role, archetype, detail, cohort=None):
    """One row per classroom.html game played. No user_id — see the DDL
    comment in init_db(); this is anonymous by construction, not by policy.
    `cohort` is an optional, self-declared short code (e.g. a teacher's
    class code) — still not personal data, just a grouping key."""
    payload = json.dumps(detail)[:5000]
    with _conn() as conn:
        cur = conn.cursor()
        cur.execute(
            f"INSERT INTO classroom_plays (game, role, archetype, detail_json, cohort, created_at) VALUES ({_ph(6)})",
            (game, role, archetype, payload, cohort, time.time()),
        )


def get_classroom_plays(game, cohort=None, limit=500):
    """Most recent plays of one game, newest first, detail_json parsed.
    Aggregation into game-specific stats happens in server.py — this layer
    just fetches and deserializes, it doesn't know what a 'sent' or an
    'offer' means for any particular game. When `cohort` is given, only
    plays tagged with that exact code are returned."""
    mark = "%s" if IS_POSTGRES else "?"
    with _conn() as conn:
        cur = conn.cursor()
        if cohort:
            cur.execute(
                f"SELECT role, archetype, detail_json, created_at FROM classroom_plays "
                f"WHERE game = {mark} AND cohort = {mark} ORDER BY created_at DESC LIMIT {mark}",
                (game, cohort, limit),
            )
        else:
            cur.execute(
                f"SELECT role, archetype, detail_json, created_at FROM classroom_plays "
                f"WHERE game = {mark} ORDER BY created_at DESC LIMIT {mark}",
                (game, limit),
            )
        rows = cur.fetchall()
    plays = []
    for role, archetype, detail_json, created_at in rows:
        try:
            detail = json.loads(detail_json)
        except (TypeError, ValueError):
            detail = {}
        plays.append({"role": role, "archetype": archetype, "detail": detail, "created_at": created_at})
    return plays


def record_profile_nudge(user_id, axis, delta, source):
    with _conn() as conn:
        cur = conn.cursor()
        cur.execute(
            f"INSERT INTO profile_nudge_log (user_id, axis, delta, source, created_at) VALUES ({_ph(5)})",
            (user_id, axis, delta, source, time.time()),
        )


def get_profile_nudge_log(user_id, limit=20):
    mark = "%s" if IS_POSTGRES else "?"
    with _conn() as conn:
        cur = conn.cursor()
        cur.execute(
            f"SELECT axis, delta, source, created_at FROM profile_nudge_log "
            f"WHERE user_id = {mark} ORDER BY created_at DESC LIMIT {mark}",
            (user_id, limit),
        )
        rows = cur.fetchall()
    return [{"axis": a, "delta": d, "source": s, "created_at": c} for a, d, s, c in rows]


def upsert_subscription(user_id, provider, provider_customer_id, provider_subscription_id,
                         plan, status, current_period_end):
    """First thing that ever writes to `subscriptions` (see the DDL comment
    in init_db()) — called from the Stripe webhook handler. Keyed on
    provider_subscription_id so repeated webhook deliveries for the same
    subscription (Stripe retries on any non-2xx) update the same row instead
    of creating duplicates."""
    now = time.time()
    with _conn() as conn:
        cur = conn.cursor()
        mark = "%s" if IS_POSTGRES else "?"
        cur.execute(
            f"SELECT id FROM subscriptions WHERE provider_subscription_id = {mark}",
            (provider_subscription_id,),
        )
        row = cur.fetchone()
        if row:
            cur.execute(
                f"UPDATE subscriptions SET plan = {mark}, status = {mark}, "
                f"current_period_end = {mark}, updated_at = {mark} WHERE id = {mark}",
                (plan, status, current_period_end, now, row[0]),
            )
        else:
            cur.execute(
                f"INSERT INTO subscriptions (user_id, provider, provider_customer_id, "
                f"provider_subscription_id, plan, status, current_period_end, created_at, updated_at) "
                f"VALUES ({_ph(9)})",
                (user_id, provider, provider_customer_id, provider_subscription_id,
                 plan, status, current_period_end, now, now),
            )


def get_subscription(user_id):
    mark = "%s" if IS_POSTGRES else "?"
    with _conn() as conn:
        cur = conn.cursor()
        cur.execute(
            f"SELECT plan, status, current_period_end FROM subscriptions "
            f"WHERE user_id = {mark} ORDER BY updated_at DESC LIMIT 1",
            (user_id,),
        )
        row = cur.fetchone()
    if not row:
        return None
    return {"plan": row[0], "status": row[1], "current_period_end": row[2]}


def record_turtle_session(user_id, rounds, final_rule_equity, final_player_equity, override_count):
    payload = json.dumps(rounds)[:20000]
    with _conn() as conn:
        cur = conn.cursor()
        cur.execute(
            f"INSERT INTO turtle_sessions (user_id, rounds_json, final_rule_equity, "
            f"final_player_equity, override_count, created_at) VALUES ({_ph(6)})",
            (user_id, payload, final_rule_equity, final_player_equity, override_count, time.time()),
        )


def get_turtle_sessions(user_id, limit=20):
    mark = "%s" if IS_POSTGRES else "?"
    with _conn() as conn:
        cur = conn.cursor()
        cur.execute(
            f"SELECT final_rule_equity, final_player_equity, override_count, created_at "
            f"FROM turtle_sessions WHERE user_id = {mark} ORDER BY created_at DESC LIMIT {mark}",
            (user_id, limit),
        )
        rows = cur.fetchall()
    return [
        {"final_rule_equity": r[0], "final_player_equity": r[1], "override_count": r[2], "created_at": r[3]}
        for r in rows
    ]


def log_agent_tool_call(run_id, user_id, persona, tool_name, tool_input, tool_output, status, error_message=None):
    """One row per tool call the coaching agent makes — see
    coach_agent.py's ToolCallLogger. Truncated the same defensive way as
    every other free-text column in this file (log_event's payload,
    save_user_profile's blob, etc.) since this ultimately comes from model
    and tool output, not a bounded internal value."""
    with _conn() as conn:
        cur = conn.cursor()
        cur.execute(
            f"""INSERT INTO agent_tool_calls
                (run_id, user_id, persona, tool_name, tool_input, tool_output, status, error_message, created_at)
                VALUES ({_ph(9)})""",
            (
                str(run_id)[:64], user_id, persona, str(tool_name)[:80],
                str(tool_input)[:2000] if tool_input is not None else None,
                str(tool_output)[:2000] if tool_output is not None else None,
                str(status)[:20], str(error_message)[:500] if error_message else None,
                time.time(),
            ),
        )


def get_recent_agent_tool_calls(limit=50):
    """Queryable trace for the researcher/admin view — see
    /api/admin/agent-tool-calls in server.py."""
    mark = "%s" if IS_POSTGRES else "?"
    with _conn() as conn:
        cur = conn.cursor()
        cur.execute(
            f"""SELECT run_id, user_id, persona, tool_name, tool_input, tool_output,
                       status, error_message, created_at
                FROM agent_tool_calls ORDER BY created_at DESC LIMIT {mark}""",
            (limit,),
        )
        rows = cur.fetchall()
    return [
        {
            "run_id": r[0], "user_id": r[1], "persona": r[2], "tool_name": r[3],
            "tool_input": r[4], "tool_output": r[5], "status": r[6],
            "error_message": r[7], "created_at": r[8],
        }
        for r in rows
    ]
