// Footer year + privacy/terms modal, shared by index.html and dashboard.html.
// Content is intentionally plain-language placeholder text: it states the
// real posture of the app (educational, illustrative data) but should be
// reviewed by counsel before you rely on it publicly.

(function () {
  const yearEl = document.getElementById("year");
  if (yearEl) yearEl.textContent = new Date().getFullYear();

  const LEGAL = {
    privacy: {
      title: "Privacy",
      html: `
        <p class="legal-updated">Last updated: 2026</p>
        <p>FinPerson is an educational tool. This summary describes how the app is intended to handle your information; it is a plain-language placeholder and should be reviewed by a qualified professional before public use.</p>
        <h4>What we store</h4>
        <p>Your chosen persona and quiz result are stored in your browser's local storage so the app can remember them between visits. This never leaves your device unless you are signed in and a backend is connected.</p>
        <h4>Sign-in</h4>
        <p>If you sign in with Google, we receive your name, email, and profile picture to identify your account. We never receive your Google password. When a backend is connected, your sign-in token is verified server-side and not stored in the browser beyond what's needed to keep you signed in.</p>
        <h4>Sandbox data</h4>
        <p>The financial figures in the sandbox are illustrative and generated by the app. They are not linked to your real accounts unless you explicitly connect a data source.</p>
        <h4>Your choices</h4>
        <p>You can sign out at any time, which clears your stored session. Clearing your browser data removes your saved persona and quiz result.</p>
      `,
    },
    terms: {
      title: "Terms of Use",
      html: `
        <p class="legal-updated">Last updated: 2026</p>
        <p>By using FinPerson you agree to the following. This is plain-language placeholder text and should be reviewed by counsel before public use.</p>
        <h4>Educational use only</h4>
        <p>FinPerson is provided for educational and informational purposes. It does not provide financial, investment, tax, or legal advice, and nothing in the app should be treated as a recommendation to take or refrain from any financial action.</p>
        <h4>No guarantees</h4>
        <p>The scenarios and figures are illustrative and simplified. Real financial outcomes depend on factors the app does not model. We make no warranty as to accuracy, completeness, or fitness for a particular purpose.</p>
        <h4>Your responsibility</h4>
        <p>You are responsible for your own financial decisions. Consult a licensed professional before acting on anything you learn here.</p>
        <h4>Availability</h4>
        <p>The service is provided "as is" and may change or become unavailable at any time.</p>
      `,
    },
  };

  const overlay = document.getElementById("legal-overlay");
  if (!overlay) return;
  const titleEl = document.getElementById("legal-title");
  const bodyEl = document.getElementById("legal-body");
  const closeBtn = document.getElementById("legal-close");
  let triggerEl = null;

  function openLegal(kind) {
    const entry = LEGAL[kind];
    if (!entry) return;
    triggerEl = document.activeElement;
    titleEl.textContent = entry.title;
    bodyEl.innerHTML = entry.html;
    overlay.classList.add("open");
    document.body.style.overflow = "hidden";
    closeBtn.focus();
    document.addEventListener("keydown", onKeydown);
  }

  function closeLegal() {
    overlay.classList.remove("open");
    document.body.style.overflow = "";
    document.removeEventListener("keydown", onKeydown);
    if (triggerEl) triggerEl.focus();
  }

  function onKeydown(e) {
    if (e.key === "Escape") closeLegal();
  }

  document.querySelectorAll("[data-legal]").forEach(link => {
    link.addEventListener("click", e => {
      e.preventDefault();
      openLegal(link.dataset.legal);
    });
  });

  closeBtn.addEventListener("click", closeLegal);
  overlay.addEventListener("click", e => {
    if (e.target === overlay) closeLegal();
  });
})();
