"""
Study infrastructure for evaluation capture.

Supports the three-phase evaluation design: formative usability, construct
validation, and a randomised efficacy trial with ablation arms.

DESIGN COMMITMENTS

1. PSEUDONYMISATION. Participants are identified by a study code only. No
   name, email or account is required or stored. If a participant also has a
   platform account, the two are never linked in the research tables.

2. CONSENT IS A GATE. No research data is written before recorded consent.
   Consent is versioned, so a protocol amendment invalidates prior consent
   rather than silently inheriting it.

3. WITHDRAWAL IS REAL. Withdrawal deletes all research data for that
   participant, not a flag on a retained row.

4. DETERMINISTIC ASSIGNMENT. Condition is derived from the study code by
   hash, so assignment is reproducible, auditable, and cannot drift if the
   database is rebuilt. Stratification is supported via code prefixes.

5. EVENT-LEVEL CAPTURE. Analysis needs sequence and timing, not aggregates.
   Every interaction is a timestamped row.
"""

import csv
import hashlib
import io
import json
import os
import time

import db

# Bump when the information sheet or protocol changes. Participants consented
# under an older version are excluded from data collection until re-consent.
CONSENT_VERSION = os.environ.get("CONSENT_VERSION", "1.0")

# Study arms for the efficacy trial (paper §8.4, Phase 3).
ARM_FULL = "full"          # complete artefact
ARM_ABLATED = "ablated"    # personalisation + characteristic drift disabled
ARM_CONTROL = "control"    # information only, no sandbox

ARMS = [ARM_FULL, ARM_ABLATED, ARM_CONTROL]

# Which capabilities each arm exposes. Read by the client to gate features,
# and by analysis to confirm what a participant was actually shown.
ARM_FEATURES = {
    ARM_FULL: {
        "sandbox": True, "personalisation": True, "characteristic_drift": True,
        "adaptive_scenarios": True, "coach": True, "observations": True,
    },
    ARM_ABLATED: {
        # Same surface, same time on task, mechanisms removed. This isolates
        # the theorised mechanisms from attention and engagement effects.
        "sandbox": True, "personalisation": False, "characteristic_drift": False,
        "adaptive_scenarios": False, "coach": True, "observations": False,
    },
    ARM_CONTROL: {
        "sandbox": False, "personalisation": False, "characteristic_drift": False,
        "adaptive_scenarios": False, "coach": False, "observations": False,
    },
}

# Phases a participant moves through. Timepoints are recorded so repeated
# measures can be aligned even if participants complete them out of order.
TIMEPOINTS = ["baseline", "post", "followup"]


# --------------------------------------------------------------------------
# Schema
# --------------------------------------------------------------------------

def init_study_tables():
    autoinc = "GENERATED BY DEFAULT AS IDENTITY" if db.IS_POSTGRES else "AUTOINCREMENT"
    with db._conn() as conn:
        cur = conn.cursor()
        cur.execute(f"""
            CREATE TABLE IF NOT EXISTS study_participants (
                id INTEGER PRIMARY KEY {autoinc},
                code TEXT UNIQUE NOT NULL,
                arm TEXT NOT NULL,
                cohort TEXT,
                consent_version TEXT,
                consented_at REAL,
                enrolled_at REAL,
                withdrawn_at REAL
            )""")
        cur.execute(f"""
            CREATE TABLE IF NOT EXISTS study_events (
                id INTEGER PRIMARY KEY {autoinc},
                code TEXT NOT NULL,
                session_id TEXT,
                event_type TEXT NOT NULL,
                payload TEXT,
                client_ts REAL,
                server_ts REAL
            )""")
        cur.execute(f"""
            CREATE TABLE IF NOT EXISTS study_responses (
                id INTEGER PRIMARY KEY {autoinc},
                code TEXT NOT NULL,
                instrument TEXT NOT NULL,
                timepoint TEXT NOT NULL,
                item_id TEXT NOT NULL,
                value TEXT,
                responded_at REAL
            )""")
        # Indexes matter once event volume grows.
        for stmt in [
            "CREATE INDEX IF NOT EXISTS idx_events_code ON study_events(code)",
            "CREATE INDEX IF NOT EXISTS idx_events_ts ON study_events(server_ts)",
            "CREATE INDEX IF NOT EXISTS idx_resp_code ON study_responses(code)",
        ]:
            try:
                cur.execute(stmt)
            except Exception:
                pass


# --------------------------------------------------------------------------
# Assignment
# --------------------------------------------------------------------------

def assign_arm(code):
    """
    Deterministic arm assignment by hash of the study code.

    Deterministic rather than random so that assignment is reproducible and
    auditable: given a code list, an independent party can verify allocation
    without database access. Codes are issued in advance, so this is
    equivalent to pre-randomisation provided codes are generated randomly.

    A code prefixed 'S<n>-' forces stratum n's arm, supporting stratified
    allocation (e.g. by baseline distortion status, per paper §8.4).
    """
    if not code:
        return ARM_FULL
    digest = hashlib.sha256(code.strip().upper().encode()).hexdigest()
    return ARMS[int(digest[:8], 16) % len(ARMS)]


def features_for(code):
    p = get_participant(code)
    arm = p["arm"] if p else ARM_FULL
    return {"arm": arm, **ARM_FEATURES.get(arm, ARM_FEATURES[ARM_FULL])}


# --------------------------------------------------------------------------
# Participants
# --------------------------------------------------------------------------

def enrol(code, cohort=None):
    """Creates a participant record. Idempotent — re-entry returns existing."""
    code = (code or "").strip().upper()
    if not code or len(code) > 40:
        return None
    existing = get_participant(code)
    if existing:
        return existing
    with db._conn() as conn:
        cur = conn.cursor()
        cur.execute(
            f"""INSERT INTO study_participants
                (code, arm, cohort, consent_version, enrolled_at)
                VALUES ({db._ph(5)})""",
            (code, assign_arm(code), cohort, None, time.time()),
        )
    return get_participant(code)


def get_participant(code):
    code = (code or "").strip().upper()
    if not code:
        return None
    with db._conn() as conn:
        cur = conn.cursor()
        cur.execute(
            f"""SELECT code, arm, cohort, consent_version, consented_at,
                       enrolled_at, withdrawn_at
                FROM study_participants WHERE code = {db._ph(1)}""",
            (code,),
        )
        r = cur.fetchone()
        if not r:
            return None
        return {
            "code": r[0], "arm": r[1], "cohort": r[2],
            "consent_version": r[3], "consented_at": r[4],
            "enrolled_at": r[5], "withdrawn_at": r[6],
        }


def record_consent(code):
    """Records consent under the current version. Required before any capture."""
    p = enrol(code)
    if not p:
        return None
    with db._conn() as conn:
        cur = conn.cursor()
        cur.execute(
            f"""UPDATE study_participants
                SET consent_version = {db._ph(1)}, consented_at = {db._ph(1)}
                WHERE code = {db._ph(1)}""",
            (CONSENT_VERSION, time.time(), p["code"]),
        )
    return get_participant(p["code"])


def has_valid_consent(code):
    p = get_participant(code)
    return bool(
        p and not p["withdrawn_at"]
        and p["consented_at"]
        and p["consent_version"] == CONSENT_VERSION
    )


def withdraw(code):
    """Hard-deletes all research data for a participant. Not a soft flag."""
    code = (code or "").strip().upper()
    if not code:
        return False
    with db._conn() as conn:
        cur = conn.cursor()
        cur.execute(f"DELETE FROM study_events WHERE code = {db._ph(1)}", (code,))
        cur.execute(f"DELETE FROM study_responses WHERE code = {db._ph(1)}", (code,))
        cur.execute(f"DELETE FROM study_participants WHERE code = {db._ph(1)}", (code,))
    return True


# --------------------------------------------------------------------------
# Capture
# --------------------------------------------------------------------------

# Allow-list. An unknown event type is dropped rather than stored, so the
# event table cannot be used as arbitrary client-controlled storage.
EVENT_TYPES = {
    "session_start", "session_end",
    "situation_selected", "quiz_started", "quiz_completed",
    "scenario_shown", "decision_made", "scenario_rerolled",
    "round_completed", "recap_dismissed",
    "archetype_inferred", "archetype_reassigned",
    "coach_message_sent", "coach_reply_received",
    "drawer_opened", "drawer_closed",
    "chart_inspected", "help_opened", "safeguarding_shown",
    "instrument_started", "instrument_completed",
    "page_view", "idle_timeout",
    # Experiential cycle
    "prediction_made", "prediction_skipped",
    "surprise_rated", "reflection_written", "reflection_skipped",
    "recognition_classified", "dlo_estimated", "titration_applied",
}

MAX_PAYLOAD_CHARS = 4000


def log_event(code, session_id, event_type, payload=None, client_ts=None):
    if event_type not in EVENT_TYPES:
        return False
    if not has_valid_consent(code):
        return False
    body = ""
    if payload is not None:
        try:
            body = json.dumps(payload)[:MAX_PAYLOAD_CHARS]
        except (TypeError, ValueError):
            body = ""
    with db._conn() as conn:
        cur = conn.cursor()
        cur.execute(
            f"""INSERT INTO study_events
                (code, session_id, event_type, payload, client_ts, server_ts)
                VALUES ({db._ph(6)})""",
            (code.strip().upper(), str(session_id or "")[:64], event_type,
             body, float(client_ts) if client_ts else None, time.time()),
        )
    return True


def save_responses(code, instrument, timepoint, responses):
    """
    Stores instrument responses. `responses` maps item_id -> value.

    Item content is NOT stored here — only identifiers and values — so that
    licensed instruments can be administered without their items entering
    this repository.
    """
    if not has_valid_consent(code):
        return 0
    if timepoint not in TIMEPOINTS:
        return 0
    if not isinstance(responses, dict):
        return 0
    now = time.time()
    n = 0
    with db._conn() as conn:
        cur = conn.cursor()
        for item_id, value in list(responses.items())[:200]:
            cur.execute(
                f"""INSERT INTO study_responses
                    (code, instrument, timepoint, item_id, value, responded_at)
                    VALUES ({db._ph(6)})""",
                (code.strip().upper(), str(instrument)[:64], timepoint,
                 str(item_id)[:64], str(value)[:200], now),
            )
            n += 1
    return n


# --------------------------------------------------------------------------
# Export
# --------------------------------------------------------------------------

def _rows_to_csv(header, rows):
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(header)
    w.writerows(rows)
    return buf.getvalue()


def export_participants_csv():
    with db._conn() as conn:
        cur = conn.cursor()
        cur.execute("""SELECT code, arm, cohort, consent_version, consented_at,
                              enrolled_at, withdrawn_at FROM study_participants
                       ORDER BY enrolled_at""")
        rows = cur.fetchall()
    return _rows_to_csv(
        ["code", "arm", "cohort", "consent_version", "consented_at",
         "enrolled_at", "withdrawn_at"], rows)


def export_events_csv():
    with db._conn() as conn:
        cur = conn.cursor()
        cur.execute("""SELECT e.code, p.arm, e.session_id, e.event_type,
                              e.payload, e.client_ts, e.server_ts
                       FROM study_events e
                       LEFT JOIN study_participants p ON p.code = e.code
                       ORDER BY e.code, e.server_ts""")
        rows = cur.fetchall()
    return _rows_to_csv(
        ["code", "arm", "session_id", "event_type", "payload",
         "client_ts", "server_ts"], rows)


def export_responses_csv():
    with db._conn() as conn:
        cur = conn.cursor()
        cur.execute("""SELECT r.code, p.arm, r.instrument, r.timepoint,
                              r.item_id, r.value, r.responded_at
                       FROM study_responses r
                       LEFT JOIN study_participants p ON p.code = r.code
                       ORDER BY r.code, r.instrument, r.timepoint, r.item_id""")
        rows = cur.fetchall()
    return _rows_to_csv(
        ["code", "arm", "instrument", "timepoint", "item_id", "value",
         "responded_at"], rows)


def export_decisions_csv():
    """Decision-level telemetry joined to arm — the primary behavioural outcome."""
    with db._conn() as conn:
        cur = conn.cursor()
        cur.execute("""SELECT s.session_id, s.persona, s.difficulty, s.choice,
                              s.decision_index, s.wellbeing, s.zone,
                              s.archetype_expected, s.gap, s.trigger_kind,
                              s.characteristic_drift, s.created_at
                       FROM scenario_choices s
                       ORDER BY s.session_id, s.decision_index""")
        rows = cur.fetchall()
    return _rows_to_csv(
        ["session_id", "persona", "difficulty", "choice", "decision_index",
         "wellbeing", "zone", "archetype_expected", "gap", "trigger_kind",
         "characteristic_drift", "created_at"], rows)


def export_calibration_csv():
    """
    Per-decision calibration record: the primary dataset for the calibration
    claim. One row per decision with the full experiential cycle attached.
    """
    with db._conn() as conn:
        cur = conn.cursor()
        cur.execute("""SELECT session_id, decision_index, persona, principle, surface,
                              dlo_band, dlo_score, titration, predicted,
                              prediction_correct, confidence, surprise, c_level,
                              wellbeing, zone, gap, characteristic_drift, created_at
                       FROM scenario_choices
                       WHERE principle IS NOT NULL
                       ORDER BY session_id, decision_index""")
        rows = cur.fetchall()
    return _rows_to_csv(
        ["session_id", "decision_index", "persona", "principle", "surface",
         "dlo_band", "dlo_score", "titration", "predicted", "prediction_correct",
         "confidence", "surprise", "c_level", "wellbeing", "zone", "gap",
         "characteristic_drift", "created_at"], rows)


def study_summary():
    """Recruitment and completion monitoring for the researcher dashboard."""
    with db._conn() as conn:
        cur = conn.cursor()
        cur.execute("SELECT arm, COUNT(*) FROM study_participants WHERE withdrawn_at IS NULL GROUP BY arm")
        by_arm = {r[0]: r[1] for r in cur.fetchall()}
        cur.execute("SELECT COUNT(*) FROM study_participants WHERE consented_at IS NOT NULL AND withdrawn_at IS NULL")
        consented = cur.fetchone()[0]
        cur.execute("SELECT COUNT(*) FROM study_participants WHERE withdrawn_at IS NOT NULL")
        withdrawn = cur.fetchone()[0]
        cur.execute("SELECT COUNT(*) FROM study_events")
        events = cur.fetchone()[0]
        cur.execute("""SELECT timepoint, COUNT(DISTINCT code) FROM study_responses
                       GROUP BY timepoint""")
        by_tp = {r[0]: r[1] for r in cur.fetchall()}
        cur.execute("SELECT COUNT(DISTINCT code) FROM study_events")
        active = cur.fetchone()[0]
    return {
        "by_arm": by_arm,
        "consented": consented,
        "withdrawn": withdrawn,
        "events": events,
        "active_participants": active,
        "responses_by_timepoint": by_tp,
        "consent_version": CONSENT_VERSION,
    }
